const express = require("express");
const route = express.Router();
const adminRouter = require("./adminRouter");
const dietRouter = require("./dietRouter");
const alletgieRouter = require("./allergieRouter");
const userRouter = require("./userRouter");
const categoryRouter = require("./categorRouter");
const cuisineRouter = require("./cuisineRouter");
const mealRouter = require("./mealRouter");
const recipeRouter = require("./recipeRouter");
const ingredientUnitRouter = require("./ingredientunitRouter");
const stepRouter = require("./stepRouter");
const ingredientRouter = require("./ingredientRouter");
const nutritionRouter = require("./nutritionRouter");
const notificationRouter = require("./notificationRouter");
const generalsettingRouter = require("./generalsettingRouter");
const planRouter = require("./planRouter");
const commentRouter = require("./commentRouter");
const ratingRoute = require("./ratingRouter");
const dashboardRouter = require("./dashboardRouter");
const paymentRouter = require("./paymentRouter");

// Use router in index
route.use("/admin", adminRouter);
route.use("/admin/diet", dietRouter);
route.use("/admin/allergie", alletgieRouter);
route.use("/admin/user", userRouter);
route.use("/admin/category", categoryRouter);
route.use("/admin/cuisine", cuisineRouter);
route.use("/admin/meal", mealRouter);
route.use("/admin/recipe", recipeRouter);
route.use("/admin/ingredientunit", ingredientUnitRouter);
route.use("/admin/step", stepRouter);
route.use("/admin/ingredient", ingredientRouter);
route.use("/admin/nutrition", nutritionRouter);
route.use("/admin/notification", notificationRouter);
route.use("/admin/generalsetting", generalsettingRouter);
route.use("/admin/plan", planRouter);
route.use("/admin/comment", commentRouter);
route.use("/admin/rating", ratingRoute);
route.use("/admin/dashboard", dashboardRouter);
route.use("/admin/payment", paymentRouter);

module.exports = route;
